server:
  port: 18087
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
spring:
  thymeleaf:
    cache: false
  application:
    name: item
  main:
    allow-bean-definition-overriding: true

pagepath: D:/Chuanzhiboke/changgou/changgou/changgouparent/changgou-web/changgou-web-item/src/main/resources/templates/items